// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: rootfs_server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rootfs_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rootfs_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_rootfs_server_proto_rawDescGZIP(), []int{0}
}

func (x *AbortRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommandsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
}

func (x *CommandsResponse) Reset() {
	*x = CommandsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rootfs_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandsResponse) ProtoMessage() {}

func (x *CommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rootfs_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandsResponse.ProtoReflect.Descriptor instead.
func (*CommandsResponse) Descriptor() ([]byte, []int) {
	return file_rootfs_server_proto_rawDescGZIP(), []int{1}
}

func (x *CommandsResponse) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rootfs_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rootfs_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rootfs_server_proto_rawDescGZIP(), []int{2}
}

type LogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line []string `protobuf:"bytes,1,rep,name=line,proto3" json:"line,omitempty"`
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rootfs_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rootfs_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_rootfs_server_proto_rawDescGZIP(), []int{3}
}

func (x *LogMessage) GetLine() []string {
	if x != nil {
		return x.Line
	}
	return nil
}

type ResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path  string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Stage string `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rootfs_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rootfs_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_rootfs_server_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ResourceRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

// A single resource path maps to one or multiple resources.
// The targetPath indicates the actual file where the resource must be written to.
type ResourceChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*ResourceChunk_Header
	//	*ResourceChunk_Chunk
	//	*ResourceChunk_Eof
	Payload isResourceChunk_Payload `protobuf_oneof:"payload"`
}

func (x *ResourceChunk) Reset() {
	*x = ResourceChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rootfs_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceChunk) ProtoMessage() {}

func (x *ResourceChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rootfs_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceChunk.ProtoReflect.Descriptor instead.
func (*ResourceChunk) Descriptor() ([]byte, []int) {
	return file_rootfs_server_proto_rawDescGZIP(), []int{5}
}

func (m *ResourceChunk) GetPayload() isResourceChunk_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ResourceChunk) GetHeader() *ResourceChunk_ResourceHeader {
	if x, ok := x.GetPayload().(*ResourceChunk_Header); ok {
		return x.Header
	}
	return nil
}

func (x *ResourceChunk) GetChunk() *ResourceChunk_ResourceContents {
	if x, ok := x.GetPayload().(*ResourceChunk_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (x *ResourceChunk) GetEof() *ResourceChunk_ResourceEof {
	if x, ok := x.GetPayload().(*ResourceChunk_Eof); ok {
		return x.Eof
	}
	return nil
}

type isResourceChunk_Payload interface {
	isResourceChunk_Payload()
}

type ResourceChunk_Header struct {
	Header *ResourceChunk_ResourceHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type ResourceChunk_Chunk struct {
	Chunk *ResourceChunk_ResourceContents `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type ResourceChunk_Eof struct {
	Eof *ResourceChunk_ResourceEof `protobuf:"bytes,3,opt,name=eof,proto3,oneof"`
}

func (*ResourceChunk_Header) isResourceChunk_Payload() {}

func (*ResourceChunk_Chunk) isResourceChunk_Payload() {}

func (*ResourceChunk_Eof) isResourceChunk_Payload() {}

type ResourceChunk_ResourceHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourcePath    string `protobuf:"bytes,1,opt,name=sourcePath,proto3" json:"sourcePath,omitempty"`
	TargetPath    string `protobuf:"bytes,2,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
	FileMode      int64  `protobuf:"varint,3,opt,name=fileMode,proto3" json:"fileMode,omitempty"`
	IsDir         bool   `protobuf:"varint,4,opt,name=isDir,proto3" json:"isDir,omitempty"`
	TargetUser    string `protobuf:"bytes,5,opt,name=targetUser,proto3" json:"targetUser,omitempty"`
	TargetWorkdir string `protobuf:"bytes,6,opt,name=targetWorkdir,proto3" json:"targetWorkdir,omitempty"`
	Id            string `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ResourceChunk_ResourceHeader) Reset() {
	*x = ResourceChunk_ResourceHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rootfs_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceChunk_ResourceHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceChunk_ResourceHeader) ProtoMessage() {}

func (x *ResourceChunk_ResourceHeader) ProtoReflect() protoreflect.Message {
	mi := &file_rootfs_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceChunk_ResourceHeader.ProtoReflect.Descriptor instead.
func (*ResourceChunk_ResourceHeader) Descriptor() ([]byte, []int) {
	return file_rootfs_server_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ResourceChunk_ResourceHeader) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *ResourceChunk_ResourceHeader) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *ResourceChunk_ResourceHeader) GetFileMode() int64 {
	if x != nil {
		return x.FileMode
	}
	return 0
}

func (x *ResourceChunk_ResourceHeader) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *ResourceChunk_ResourceHeader) GetTargetUser() string {
	if x != nil {
		return x.TargetUser
	}
	return ""
}

func (x *ResourceChunk_ResourceHeader) GetTargetWorkdir() string {
	if x != nil {
		return x.TargetWorkdir
	}
	return ""
}

func (x *ResourceChunk_ResourceHeader) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResourceChunk_ResourceContents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk    []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Checksum []byte `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Id       string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ResourceChunk_ResourceContents) Reset() {
	*x = ResourceChunk_ResourceContents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rootfs_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceChunk_ResourceContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceChunk_ResourceContents) ProtoMessage() {}

func (x *ResourceChunk_ResourceContents) ProtoReflect() protoreflect.Message {
	mi := &file_rootfs_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceChunk_ResourceContents.ProtoReflect.Descriptor instead.
func (*ResourceChunk_ResourceContents) Descriptor() ([]byte, []int) {
	return file_rootfs_server_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ResourceChunk_ResourceContents) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ResourceChunk_ResourceContents) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *ResourceChunk_ResourceContents) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResourceChunk_ResourceEof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ResourceChunk_ResourceEof) Reset() {
	*x = ResourceChunk_ResourceEof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rootfs_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceChunk_ResourceEof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceChunk_ResourceEof) ProtoMessage() {}

func (x *ResourceChunk_ResourceEof) ProtoReflect() protoreflect.Message {
	mi := &file_rootfs_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceChunk_ResourceEof.ProtoReflect.Descriptor instead.
func (*ResourceChunk_ResourceEof) Descriptor() ([]byte, []int) {
	return file_rootfs_server_proto_rawDescGZIP(), []int{5, 2}
}

func (x *ResourceChunk_ResourceEof) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_rootfs_server_proto protoreflect.FileDescriptor

var file_rootfs_server_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0c,
	0x41, 0x62, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x20, 0x0a, 0x0a, 0x4c, 0x6f, 0x67,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x3b, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x22, 0x9e, 0x04, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x3d, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x05, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x48,
	0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x34, 0x0a, 0x03, 0x65, 0x6f, 0x66, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x45, 0x6f, 0x66, 0x48, 0x00, 0x52, 0x03, 0x65, 0x6f, 0x66, 0x1a, 0xd8,
	0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x73, 0x44, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73,
	0x44, 0x69, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x57, 0x6f, 0x72,
	0x6b, 0x64, 0x69, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x64, 0x69, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x54, 0x0a, 0x10, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a,
	0x1d, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x6f, 0x66, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0xa6, 0x02, 0x0a, 0x0c, 0x52, 0x6f,
	0x6f, 0x74, 0x66, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x08, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x12, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x64,
	0x45, 0x72, 0x72, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x2a, 0x0a, 0x05, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x25, 0x0a, 0x07, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x6f, 0x6d, 0x62, 0x75, 0x73, 0x74, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x66, 0x69,
	0x72, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rootfs_server_proto_rawDescOnce sync.Once
	file_rootfs_server_proto_rawDescData = file_rootfs_server_proto_rawDesc
)

func file_rootfs_server_proto_rawDescGZIP() []byte {
	file_rootfs_server_proto_rawDescOnce.Do(func() {
		file_rootfs_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_rootfs_server_proto_rawDescData)
	})
	return file_rootfs_server_proto_rawDescData
}

var file_rootfs_server_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rootfs_server_proto_goTypes = []interface{}{
	(*AbortRequest)(nil),                   // 0: proto.AbortRequest
	(*CommandsResponse)(nil),               // 1: proto.CommandsResponse
	(*Empty)(nil),                          // 2: proto.Empty
	(*LogMessage)(nil),                     // 3: proto.LogMessage
	(*ResourceRequest)(nil),                // 4: proto.ResourceRequest
	(*ResourceChunk)(nil),                  // 5: proto.ResourceChunk
	(*ResourceChunk_ResourceHeader)(nil),   // 6: proto.ResourceChunk.ResourceHeader
	(*ResourceChunk_ResourceContents)(nil), // 7: proto.ResourceChunk.ResourceContents
	(*ResourceChunk_ResourceEof)(nil),      // 8: proto.ResourceChunk.ResourceEof
}
var file_rootfs_server_proto_depIdxs = []int32{
	6, // 0: proto.ResourceChunk.header:type_name -> proto.ResourceChunk.ResourceHeader
	7, // 1: proto.ResourceChunk.chunk:type_name -> proto.ResourceChunk.ResourceContents
	8, // 2: proto.ResourceChunk.eof:type_name -> proto.ResourceChunk.ResourceEof
	2, // 3: proto.RootfsServer.Commands:input_type -> proto.Empty
	4, // 4: proto.RootfsServer.Resource:input_type -> proto.ResourceRequest
	3, // 5: proto.RootfsServer.StdErr:input_type -> proto.LogMessage
	3, // 6: proto.RootfsServer.StdOut:input_type -> proto.LogMessage
	0, // 7: proto.RootfsServer.Abort:input_type -> proto.AbortRequest
	2, // 8: proto.RootfsServer.Success:input_type -> proto.Empty
	1, // 9: proto.RootfsServer.Commands:output_type -> proto.CommandsResponse
	5, // 10: proto.RootfsServer.Resource:output_type -> proto.ResourceChunk
	2, // 11: proto.RootfsServer.StdErr:output_type -> proto.Empty
	2, // 12: proto.RootfsServer.StdOut:output_type -> proto.Empty
	2, // 13: proto.RootfsServer.Abort:output_type -> proto.Empty
	2, // 14: proto.RootfsServer.Success:output_type -> proto.Empty
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rootfs_server_proto_init() }
func file_rootfs_server_proto_init() {
	if File_rootfs_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rootfs_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rootfs_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rootfs_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rootfs_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rootfs_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rootfs_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rootfs_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceChunk_ResourceHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rootfs_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceChunk_ResourceContents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rootfs_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceChunk_ResourceEof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rootfs_server_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ResourceChunk_Header)(nil),
		(*ResourceChunk_Chunk)(nil),
		(*ResourceChunk_Eof)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rootfs_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rootfs_server_proto_goTypes,
		DependencyIndexes: file_rootfs_server_proto_depIdxs,
		MessageInfos:      file_rootfs_server_proto_msgTypes,
	}.Build()
	File_rootfs_server_proto = out.File
	file_rootfs_server_proto_rawDesc = nil
	file_rootfs_server_proto_goTypes = nil
	file_rootfs_server_proto_depIdxs = nil
}
